In [ ]:
import numpy as np

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [ ]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [ ]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [ ]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [ ]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [ ]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

---
## Система линейных уравнений


$$Ax=b$$


$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1
\end{pmatrix}
$$

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Проверим результат:

In [ ]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

In [ ]:
# обратная матрица
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

сверим $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

matrix([[ 1.00000000e+00,  4.99600361e-16, -4.71844785e-16],
        [ 1.38777878e-16,  1.00000000e+00, -2.63677968e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

определитель:

In [ ]:
np.linalg.det(A)

-129.00000000000009